// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kzsovudptnxgwszakyoa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt6c292dWRwdG54Z3dzemFreW9hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzMzk2NjQsImV4cCI6MjA2NTkxNTY2NH0.4c_Rum2otWv7xW9YTja8gPvDb_fyaBUo_1JoV3r0JI8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);