# .github/workflows/deploy.yml
# Workflow to build and deploy a Vite-based React app to GitHub Pages

name: Deploy to GitHub Pages

on:
  # Trigger the workflow every time you push to the `main` branch
  push:
    branches: [Production]
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

# Allow this job to clone the repo and create a page deployment
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  # Build job: installs dependencies, builds the site, and uploads it as an artifact
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          # Specify the Node.js version your project uses
          node-version: 20
          # Cache npm dependencies for faster builds
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build your site
        run: npm run build
        # IMPORTANT: Make sure your vite.config.ts has the correct 'base' path.
        # It should be the name of your GitHub repository.
        # Example: export default defineConfig({ base: '/your-repo-name/' })
        env:
          # If you have environment variables, define them here
          # VITE_API_KEY: ${{ secrets.VITE_API_KEY }}
          CI: false

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Vite's default build output directory is 'dist'
          path: ./dist

  # Deploy job: takes the uploaded artifact and deploys it to GitHub Pages
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
